### ISSUE TITLE
No model weights saved

### ISSUE THREAD

**Issue by stefp** [nrehush/minknet-tree-species#1]
Please add the model weights

**Comment by nrehush** [comment]
Will be done tomorrow morning

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Stefano Puliti ***@***.***>
Gesendet: Monday, August 12, 2024 3:37:18 PM
An: nrehush/minknet-tree-species ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [nrehush/minknet-tree-species] No model weights saved (Issue #1)


Please add the model weights

**Comment by nrehush** [comment]
The model weights can be found here: https://zenodo.org/records/13310914
